### ISSUE TITLE
Chinese language support

### ISSUE THREAD

**Issue by xhruso00** [matyasbohacek/strings-translate#3]
Google translate uses "zh-CN" for simplified Chinese. Iso language codes marks this language as invalid due to more than 2 char ISO language code.

**Comment by maty-bohacek** [comment]
This issue has been resolved in commits 206ffc345b8813bb24ccbf909445cc9c00f5688e, dc55b24870a22dfc84bd22a85f0511ff84647c7b and d9997615098cb26c2e07eea4f3a06f5b8fab4d01. Not only simplified, but also traditional Chinese support has been added. A new version (`1.0.3`) has been pushed to **Pypi** and is now available.

Thank you, @xhruso00 - this was a great suggestion!
